version: "3.9"
   
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.dev.sh
    volumes:
      - staticfiles:/backend/staticfiles
      - ./backend/db.sqlite3:/backend/db.sqlite3
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  staticfiles: