version: "3.9"
   
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy
    restart: always
    entrypoint: /entrypoint.dev.sh
    environment:
      - DEBUG_MODE=true  
    volumes:
      - staticfiles:/backend/staticfiles
      - ./backend/db.sqlite3:/backend/db.sqlite3
      - ./backend:/backend 
  webserver:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
      args:
        - REACT_APP_DOCKER_ENV=true
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  staticfiles: