name: athlos-backend
type: web

services:
  - name: backend
    type: web
    instance_type: nano
    build:
      type: docker
      dockerfile: backend/Dockerfile.prod
    ports:
      - port: 8000
        protocol: http
    env:
      - name: ENVIRONMENT
        value: production
      - name: PORT
        value: "8000"
      - name: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - name: GUNICORN_WORKERS
        value: "2"
      - name: GUNICORN_THREADS
        value: "4"
      - name: GUNICORN_TIMEOUT
        value: "60"
    health_check:
      http:
        path: /
        port: 8000
    autoscaling:
      min: 1
      max: 1